In [1]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [2]:
np.array([1,23,4,4,3,24])
A = np.arange(12).reshape(-1,6)
np.arange(10, 35, 5).reshape(-1, 5)
np.linspace(-12, 1, 5) 
np.zeros_like(A) 
np.random.default_rng().random((5, 5))
np.random.default_rng().normal(0, 0.25, (5,5))
np.fromfunction(lambda i, j: i+j, (2,5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.]])

In [62]:
A.sum(axis=0), A.min(axis=1), A.max(axis=1)
np.median(A)
np.all(A[1] > 3)
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 0, b)
np.argmax(b), np.argmin(b, axis=0)
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
np.clip(b, 2, 6)
np.ceil(np.array([-1.7, 2, -0.2, 0.2])), np.floor(np.array([-1.7, 2, -0.2, 0.2]))
np.corrcoef(np.array([[1, 3, 4], [1, 3, 4]])) 
np.cross([1,2,3], [4,5,6]) # array([-3,  6, -3])
np.cumprod([[1,2,3], [4,5,6]], axis=1), np.cumsum([[1,2,3], [4,5,6]], axis=1)
h = [[1,2,3],[1,2,3],[1,2,3]]
np.inner(h,h), np.outer(h,h) #(3, 3) and (9, 9)
np.invert(np.array(0, dtype=np.uint64)) #return the biggest number of type
np.lexsort(([9, 4, 0, 4, 0, 2, 1], 
            [1, 5, 1, 4, 3, 4, 4])) # the last key is primary
np.maximum(np.eye(2), [0.5, 2]) # broadcasting
np.minimum(np.eye(2), [0.5, 2])
np.nonzero(np.array([[0, 1, 0], [5, 6, 1]]) > 1) # (array([1, 1], dtype=int64), array([0, 1], dtype=int64))
np.round(2.5), round(3.5)
np.sort([[1,4],[3,1]], axis=None) 

(array([[14, 14, 14],
        [14, 14, 14],
        [14, 14, 14]]),
 array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [2, 4, 6, 2, 4, 6, 2, 4, 6],
        [3, 6, 9, 3, 6, 9, 3, 6, 9],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [2, 4, 6, 2, 4, 6, 2, 4, 6],
        [3, 6, 9, 3, 6, 9, 3, 6, 9],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [2, 4, 6, 2, 4, 6, 2, 4, 6],
        [3, 6, 9, 3, 6, 9, 3, 6, 9]]))